//
//  MainMenuViewController.swift
//  Secure Door
//
//  Created by UHP Mac 5 on 02/02/2019.
//  Copyright (c) 2019 Jakov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MainMenuViewController: UIViewController {

    // MARK: - Public properties -

    var presenter: MainMenuPresenterInterface!
    @IBOutlet weak var usernameLabel: UILabel!
    
    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
    }
	
}

// MARK: - Extensions -

extension MainMenuViewController: MainMenuViewInterface {
}
