//
//  MainMenuPresenter.swift
//  Secure Door
//
//  Created by UHP Mac 5 on 02/02/2019.
//  Copyright (c) 2019 Jakov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MainMenuPresenter {

    weak var view: MainMenuViewInterface?
    
    // MARK: - Private properties -
    private let _wireframe: MainMenuWireframeInterface
    private let _interactor: MainMenuInteractorInterface

    // MARK: - Lifecycle -

    init(wireframe: MainMenuWireframeInterface, interactor: MainMenuInteractorInterface) {
        _wireframe = wireframe
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension MainMenuPresenter: MainMenuPresenterInterface {
    
}
