//
//  MainMenuInterfaces.swift
//  Secure Door
//
//  Created by UHP Mac 5 on 02/02/2019.
//  Copyright (c) 2019 Jakov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum MainMenuNavigationOption {
}

protocol MainMenuWireframeInterface: WireframeInterface {
    func navigate(to option: MainMenuNavigationOption)
}

protocol MainMenuViewInterface: ViewInterface {
}

protocol MainMenuPresenterInterface: PresenterInterface {
    var view:MainMenuViewInterface? { get set }
}

protocol MainMenuInteractorInterface: InteractorInterface {
}
