# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Secure Door' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Secure Door
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Swinject'
  pod 'SwinjectStoryboard'

  target 'Secure DoorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
