//
//  UsersWireframe.swift
//  Secure Door
//
//  Created by UHP Mac 5 on 05/02/2019.
//  Copyright (c) 2019 Jakov. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class UsersWireframe {

    // MARK: - Private properties -

    private weak var usersController: UsersViewController?

    // MARK: - Module setup -

    init(controller: UsersViewController) {
        usersController = controller
    }

}

// MARK: - Extensions -

extension UsersWireframe: UsersWireframeInterface {
    var viewController: UIViewController? {
        return usersController
    }
    
    var navigationController: UINavigationController? {
        return usersController?.navigationController
    }
    

    func navigate(to option: UsersNavigationOption) {
    }
}
